/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Trade } from '../types';

export const INITIAL_SEEDS: Trade[] = [
  {
    id: 't-1',
    date: '2023-12-14',
    symbol: 'BTC/USDT',
    market: 'Crypto',
    direction: 'Long',
    entryPrice: 42000,
    exitPrice: 43764,
    quantity: 0.1,
    leverage: 10,
    stopLoss: 41000,
    takeProfit: 45000,
    fees: 15.0,
    status: 'Win',
    pnl: 420.0,
    roi: 4.2,
    strategy: 'Breakout Trend',
    confluences: ['EMA Cross', 'Fib Retrace'],
    marketMood: 'Neutral',
    emotionalState: '😊',
    notes: 'Clean breakout of the key resistance at 42k. Backtested EMA alignment gave high confluence. Kept size normal.',
    screenshots: []
  },
  {
    id: 't-2',
    date: '2023-12-13',
    symbol: 'EUR/USD',
    market: 'Forex',
    direction: 'Short',
    entryPrice: 1.0925,
    exitPrice: 1.0955,
    quantity: 100000,
    leverage: 20,
    stopLoss: 1.0965,
    takeProfit: 1.0850,
    fees: 5.4,
    status: 'Loss',
    pnl: -115.4,
    roi: -1.15,
    strategy: 'News Catalyst',
    confluences: ['Volume Profile'],
    marketMood: 'Neutral',
    emotionalState: '😰',
    notes: 'CPI data sparked immediate dollar selling. Attempted to short the overextension but got caught in high volatility. Stopped out prematurely.',
    screenshots: []
  },
  {
    id: 't-3',
    date: '2023-12-12',
    symbol: 'TSLA',
    market: 'Stocks',
    direction: 'Long',
    entryPrice: 240.5,
    exitPrice: 0,
    quantity: 15,
    leverage: 1,
    stopLoss: 225.0,
    takeProfit: 275.0,
    fees: 2.5,
    status: 'Open',
    pnl: 0,
    roi: 0,
    strategy: 'Mean Reversion',
    confluences: ['RSI Divergence', 'EMA Cross'],
    marketMood: 'Neutral',
    emotionalState: '😐',
    notes: 'Daily oversold bounce setup. Waiting for momentum to shift. Entry filled on strong support pivot.',
    screenshots: []
  },
  {
    id: 't-4',
    date: '2023-12-10',
    symbol: 'ETH/USDT',
    market: 'Crypto',
    direction: 'Short',
    entryPrice: 2350,
    exitPrice: 2120,
    quantity: 5,
    leverage: 5,
    stopLoss: 2420,
    takeProfit: 2000,
    fees: 12.5,
    status: 'Win',
    pnl: 1250.0,
    roi: 12.5,
    strategy: 'Breakout Trend',
    confluences: ['EMA Cross', 'MACD', 'SR Flip'],
    marketMood: 'Ext. Greed',
    emotionalState: '🤑',
    notes: 'Beautiful rejection at local highs. Position sized and leveraged appropriately. Clean run down to key support.',
    screenshots: []
  },
  {
    id: 't-5',
    date: '2023-12-08',
    symbol: 'SPY',
    market: 'Stocks',
    direction: 'Long',
    entryPrice: 460.2,
    exitPrice: 457.2,
    quantity: 150,
    leverage: 1,
    stopLoss: 456.0,
    takeProfit: 468.0,
    fees: 5.0,
    status: 'Loss',
    pnl: -450.0,
    roi: -0.45,
    strategy: 'News Catalyst',
    confluences: ['Volume Profile'],
    marketMood: 'Ext. Greed',
    emotionalState: '😤',
    notes: 'FOMC announcement volatility whipsawed the index. Slipped past my ideal stop loss. Must avoid trading stock index around major releases.',
    screenshots: []
  },
  {
    id: 't-6',
    date: '2023-11-28',
    symbol: 'XAU/USD',
    market: 'Commodities',
    direction: 'Long',
    entryPrice: 2010.5,
    exitPrice: 2021.7,
    quantity: 100,
    leverage: 10,
    stopLoss: 2000.0,
    takeProfit: 2045.0,
    fees: 15.0,
    status: 'Win',
    pnl: 1120.0,
    roi: 11.2,
    strategy: 'Mean Reversion',
    confluences: ['RSI Divergence', 'Fib Retrace'],
    marketMood: 'Ext. Fear',
    emotionalState: '😊',
    notes: 'Gold bounce on geopolitical headlines. Entry was perfectly timed near the 50% Fib retracement level.',
    screenshots: []
  },
  {
    id: 't-7',
    date: '2023-11-15',
    symbol: 'GBP/JPY',
    market: 'Forex',
    direction: 'Long',
    entryPrice: 185.2,
    exitPrice: 187.9,
    quantity: 50000,
    leverage: 30,
    stopLoss: 184.2,
    takeProfit: 190.0,
    fees: 8.5,
    status: 'Win',
    pnl: 2450.0,
    roi: 16.2,
    strategy: 'Breakout Trend',
    confluences: ['SR Flip', 'Volume Profile'],
    marketMood: 'Neutral',
    emotionalState: '😊',
    notes: 'A clear breakout of daily consolidation. Price retested and held the support level perfectly. Kept patience and let it run.',
    screenshots: []
  },
  {
    id: 't-8',
    date: '2023-11-02',
    symbol: 'BTC/USDT',
    market: 'Crypto',
    direction: 'Short',
    entryPrice: 35400,
    exitPrice: 36240,
    quantity: 1.0,
    leverage: 10,
    stopLoss: 36240,
    takeProfit: 33000,
    fees: 20.0,
    status: 'Loss',
    pnl: -840.0,
    roi: -8.4,
    strategy: 'Fibonacci Retracement',
    confluences: ['Fib Retrace', 'MACD'],
    marketMood: 'Ext. Greed',
    emotionalState: '😤',
    notes: 'Shorting high momentum was a mistake. Stop loss was executed cleanly, but risk management was tested.',
    screenshots: []
  },
  {
    id: 't-9',
    date: '2023-10-25',
    symbol: 'EUR/USD',
    market: 'Forex',
    direction: 'Long',
    entryPrice: 1.0560,
    exitPrice: 1.0665,
    quantity: 150000,
    leverage: 20,
    stopLoss: 1.0520,
    takeProfit: 1.0750,
    fees: 10.0,
    status: 'Win',
    pnl: 1575.0,
    roi: 10.5,
    strategy: 'Mean Reversion',
    confluences: ['RSI Divergence'],
    marketMood: 'Ext. Fear',
    emotionalState: '😊',
    notes: 'Extremely oversold on the 4H charts. Divergence confirmed entry. Scaling out at major resistance.',
    screenshots: []
  },
  {
    id: 't-10',
    date: '2023-10-12',
    symbol: 'XAU/USD',
    market: 'Commodities',
    direction: 'Short',
    entryPrice: 1885.0,
    exitPrice: 1902.5,
    quantity: 80,
    leverage: 10,
    stopLoss: 1902.5,
    takeProfit: 1850.0,
    fees: 12.0,
    status: 'Loss',
    pnl: -1400.0,
    roi: -14.0,
    strategy: 'Fibonacci Retracement',
    confluences: ['Fib Retrace'],
    marketMood: 'Neutral',
    emotionalState: '😰',
    notes: 'Failed resistance short. Market broke out with extreme speed, hitting my hard stop.',
    screenshots: []
  },
  {
    id: 't-11',
    date: '2023-10-01',
    symbol: 'BTC/USDT',
    market: 'Crypto',
    direction: 'Long',
    entryPrice: 27000,
    exitPrice: 28500,
    quantity: 1.2,
    leverage: 10,
    stopLoss: 26400,
    takeProfit: 30000,
    fees: 30.0,
    status: 'Win',
    pnl: 1800.0,
    roi: 15.0,
    strategy: 'Breakout Trend',
    confluences: ['EMA Cross', 'SR Flip'],
    marketMood: 'Neutral',
    emotionalState: '😊',
    notes: 'October season breakout trend starting. Held core position despite minor dips.',
    screenshots: []
  },
  {
    id: 't-12',
    date: '2023-09-18',
    symbol: 'EUR/USD',
    market: 'Forex',
    direction: 'Short',
    entryPrice: 1.0720,
    exitPrice: 1.0650,
    quantity: 200000,
    leverage: 20,
    stopLoss: 1.0750,
    takeProfit: 1.0550,
    fees: 14.0,
    status: 'Win',
    pnl: 1400.0,
    roi: 7.0,
    strategy: 'Breakout Trend',
    confluences: ['EMA Cross', 'Volume Profile'],
    marketMood: 'Neutral',
    emotionalState: '😊',
    notes: 'Followed the bearish macro structure down. Strong support break and retest.',
    screenshots: []
  },
  {
    id: 't-13',
    date: '2023-09-05',
    symbol: 'XAU/USD',
    market: 'Commodities',
    direction: 'Long',
    entryPrice: 1920.0,
    exitPrice: 1941.5,
    quantity: 100,
    leverage: 10,
    stopLoss: 1910.0,
    takeProfit: 1950.0,
    fees: 15.0,
    status: 'Win',
    pnl: 2150.0,
    roi: 21.5,
    strategy: 'Mean Reversion',
    confluences: ['RSI Divergence', 'Fib Retrace'],
    marketMood: 'Ext. Fear',
    emotionalState: '😊',
    notes: 'Perfect golden pocket tap. Deep consolidation with momentum turning green.',
    screenshots: []
  },
  {
    id: 't-14',
    date: '2023-08-20',
    symbol: 'GBP/JPY',
    market: 'Forex',
    direction: 'Short',
    entryPrice: 186.5,
    exitPrice: 187.8,
    quantity: 100000,
    leverage: 20,
    stopLoss: 187.8,
    takeProfit: 183.0,
    fees: 12.0,
    status: 'Loss',
    pnl: -1300.0,
    roi: -1.3,
    strategy: 'News Catalyst',
    confluences: ['Volume Profile'],
    marketMood: 'Neutral',
    emotionalState: '😤',
    notes: 'Failed scalp on JPY intervention rumors. Got completely stopped on bid spike.',
    screenshots: []
  },
  {
    id: 't-15',
    date: '2023-08-01',
    symbol: 'BTC/USDT',
    market: 'Crypto',
    direction: 'Long',
    entryPrice: 29200,
    exitPrice: 30500,
    quantity: 1.5,
    leverage: 10,
    stopLoss: 28800,
    takeProfit: 32000,
    fees: 40.0,
    status: 'Win',
    pnl: 1950.0,
    roi: 13.0,
    strategy: 'Breakout Trend',
    confluences: ['Fib Retrace', 'SR Flip'],
    marketMood: 'Neutral',
    emotionalState: '😊',
    notes: 'Nice early August breakout. Position filled exactly on support retest. Scalped 50% at local resistance.',
    screenshots: []
  }
];

export const TRADING_QUOTES = [
  "Focus on the process, not the outcome. Your strategy edge will manifest over a large sample size.",
  "Letting losses run is the single most common mistake of retail traders. Cut them fast.",
  "Your emotional state dictates your risk management. Never trade when agitated, frustrated, or bored.",
  "Consistently follow your rules. A bad trade with a good outcome is still a bad trade.",
  "The goal is not to trade every single day; the goal is to execute high-probability setups.",
  "Patience is also a trading style. Sometimes doing nothing is the most profitable action.",
  "The market is a device for transferring money from the impatient to the patient.",
  "Trade what you see, not what you think. Your opinions have no influence on prices."
];
